Repository halo-dev/plugin-sitemap, pull requests merged in 2022-12, with the labels that each got.

#2 Upgrade to Halo 2.0.0
  .github/workflows/build.yml
  build.gradle
  lib/halo-2.0.0-SNAPSHOT-plain.jar
  lib/halo-2.0.0-plain.jar
  src/main/java/run/halo/sitemap/DefaultSitemapEntryLister.java
  src/main/resources/plugin.yaml
Labels: release-note-none, kind/improvement, lgtm

#3 update sitemap lastmod
  src/main/java/run/halo/sitemap/SitemapGeneratorOptions.java
  src/main/java/run/halo/sitemap/W3cDatetimeFormat.java
Labels: release-note-none, lgtm

#4 docs: refine readme
  README.md
Labels: release-note-none, kind/documentation
