Repository halo-dev/plugin-sitemap, pull requests merged in 2023-09, with the labels that each got.

#22 chore: add OWNERS file
  OWNERS
Labels: release-note-none, approved, lgtm

#19 feat: support robots.txt router
  src/main/java/run/halo/sitemap/SitemapPluginConfig.java
  src/main/resources/extensions/settings.yml
  src/main/resources/plugin.yaml
Labels: release-note, approved, lgtm

#17 chore: add app id annotation
  .github/workflows/build.yml
  README.md
  src/main/resources/plugin.yaml
Labels: release-note, approved, kind/improvement, lgtm

#21 chore: change repo organization to halo-dev
  README.md
  src/main/resources/plugin.yaml
Labels: release-note-none, approved, kind/cleanup, lgtm

#20 chore: update logo
  src/main/resources/logo.svg
  src/main/resources/plugin.yaml
Labels: release-note, approved, kind/improvement, lgtm

#24 fix: incorrect sitemap link in robots.txt
  src/main/java/run/halo/sitemap/SitemapPluginConfig.java
Labels: release-note, approved, lgtm

#25 fix: incorrect domain of loc in sitemap url entry
  build.gradle
  src/main/java/run/halo/sitemap/SitemapPluginConfig.java
Labels: kind/bug, release-note, approved, lgtm

#27 chore: update plugin devtools for project
  build.gradle
  settings.gradle
Labels: release-note-none, approved, lgtm

#26 refactor: optimize lastmod as much as possible for a fixed time
  src/main/java/run/halo/sitemap/DefaultSitemapEntryLister.java
  src/main/java/run/halo/sitemap/SitemapEntry.java
  src/main/java/run/halo/sitemap/SitemapGeneratorOptions.java
  src/main/java/run/halo/sitemap/UrlEntryMeta.java
  src/test/java/run/halo/sitemap/SitemapGeneratorOptionsTest.java
Labels: release-note, approved, kind/improvement, lgtm

#28 chore: update requires
  build.gradle
  src/main/resources/plugin.yaml
Labels: release-note-none, approved, lgtm
